# I tried to make it look like Sindres' Pure prompt

# https://starship.rs/config/#default-prompt-format
format = """
$time\
$hostname\
$shlvl\
$directory\
${custom.giturl}\
$git_branch\
${custom.git_status}\
$git_commit\
$git_status\
$git_state\
$package\
$golang\
$python\
$rust\
$deno\
$nodejs\
$cmd_duration\
$status\
$line_break\
$character"""

# this kinda adds padding top
add_newline = true

[character]
success_symbol = "[â¯](bold green)"
error_symbol = "[â¯](bold red)"

# Configure the number of directories to truncate in the current path
[directory]
#fish_style_pwd_dir_length = 1
truncation_length = 3
truncate_to_repo = true
style = "blue"

# Configure the duration of the last command
[cmd_duration]
min_time = 100
style = "fg:#cccccc"
disabled = false
format = "[ $duration]($style) "

# Branch name
[git_branch]
format = '[$branch]($style)'
symbol = "î‚ "
truncation_symbol = ""
style = "fg:#cccccc"

# Repo icon
# https://github.com/starship/starship/discussions/1252#discussioncomment-194627
[custom.giturl]
# disabled = true
description = "Display symbol for remote Git server"
command = """
GIT_REMOTE=$(command git ls-remote --get-url 2> /dev/null)
if [[ "$GIT_REMOTE" =~ "github" ]]; then
    GIT_REMOTE_SYMBOL="ïˆ "
elif [[ "$GIT_REMOTE" =~ "gitlab" ]]; then
    GIT_REMOTE_SYMBOL="ïŠ– "
elif [[ "$GIT_REMOTE" =~ "bitbucket" ]]; then
    GIT_REMOTE_SYMBOL="ï…± "
elif [[ "$GIT_REMOTE" =~ "git" ]]; then
    GIT_REMOTE_SYMBOL="ï¡ "
else
    GIT_REMOTE_SYMBOL="ï‡’ "
fi
echo "$GIT_REMOTE_SYMBOL "
"""
when = 'git rev-parse --is-inside-work-tree 2> /dev/null'
format = "$output  "
disabled = false

# show ahead behing status
[git_status]
conflicted = " ïƒ¬ "
style = "fg:#cccccc"
ahead = " â‡¡"
diverged = " â‡•â‡¡"
behind = " â‡£"
format = '[$ahead_behind](fg:bright-cyan)'
disabled = false

# show dirty git status. symbol = *
# https://github.com/starship/starship/discussions/1252#discussioncomment-692829
[custom.git_status]
when = 'test -n "$(git status --porcelain)"'
symbol = '*'
style = 'fg:#cccccc'
format = '[$symbol]($style)'

# Configure the SSH prompt
[hostname]
ssh_only = true

# Configure the background jobs
[jobs]
symbol = "ï£"

# Configure the package version
[package]
symbol = "ï£– "
style = "dimmed white"
format = "via [ğŸ $version](208 bold) "
disabled = true

# Configure the Rust module
[rust]
symbol = "î¨ "
style = "dimmed red"

# Configure the Node.js module
[nodejs]
symbol = "ï¢˜ "
style = "dimmed green"
format = ' [$version]($style)'
